### ISSUE TITLE
How did you make this illustration??

### ISSUE THREAD

**Issue by jaivardhan-bhola** [MarkMcKinney/DIY-Password-Manager#10]
**
![image](https://user-images.githubusercontent.com/83286825/146871297-5fcf5068-4f85-487e-8012-218cf765bed2.png)
**

Cómo hacer

**Comment by MarkMcKinney** [comment]
I used this site: https://carbon.now.sh

**Comment by jaivardhan-bhola** [comment]
Arigato gozaimasu
