### ISSUE TITLE
Empty input cause timedOut

### ISSUE THREAD

**Issue by gileadecastro** [MarkMcKinney/DIY-Password-Manager#5]

**Comment by MarkMcKinney** [comment]
The way the timeout function works now is that it has default input that will auto submit after 90 seconds. So, if you type nothing, it will skip the 90 seconds and simulate timing you out. Not quite sure how to fix that yet.

**Comment by ghost** [comment]
How about telling the user about the timeout ? I don't know much about python, but can the timeout function be stopped and called again, or add an exception to the code if nothing is inputted?

**Comment by MarkMcKinney** [comment]
Yeah what could be done is actually have the timeout function call the sessions close within it. Right now it submits the timeout code which is checked by the main loop. I wonder if the timeout function can detect a return?

**Comment by MarkMcKinney** [comment]
This is fixed in the new update!
